---
- hosts: all

  vars:
    packages:
      - httpd

  tasks:
    - name: uninstall httpd
      yum:
        name: "{{ item }}"
        state: absent
      with_items: "{{ packages }}"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
      become: yes
      become_user: root
      become_method: sudo
